{{- if .Values.namespace.create -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "udps.namespace" . }}
  labels:
    {{- include "udps.labels" . | nindent 4 }}
    name: {{ include "udps.namespace" . }}
{{- end }}
