{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "udps.fullname" . }}
  namespace: {{ include "udps.namespace" . }}
  labels:
    {{- include "udps.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "udps.selectorLabels" . | nindent 6 }}
{{- end }}
