apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: udps
  namespace: udps
  labels:
    app.kubernetes.io/name: udps
    app.kubernetes.io/component: availability
    app.kubernetes.io/part-of: seri-sa-platform
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: udps
      app.kubernetes.io/component: server
